
org:
  esnack24:
    uploadproduct: /app/upload/product
    uploaduser: /app/upload/user


spring:
  multipart:
    max-file-size: 5MB
    max-request-size: 20MB
    location: C:\\upload
    enabled: true